# Generated by Django 5.0.1 on 2024-01-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('big_integer_field', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('reservation_time', models.DateTimeField()),
                ('time_field', models.TimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_field', models.DurationField()),
                ('file', models.FileField(upload_to='files/')),
                ('file_path', models.FilePathField(path='/path/to/files/')),
                ('generic_ip_address_field', models.GenericIPAddressField()),
                ('image_field', models.ImageField(upload_to='images/')),
                ('slug_field', models.SlugField()),
                ('text', models.TextField()),
            ],
        ),
    ]
