# Generated by Django 5.0.1 on 2024-01-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_mymodel_decimal_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='decimal_field',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
