# Generated by Django 5.0.1 on 2024-01-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_mymodel_decimal_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='generic_ip_address_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='image_field',
        ),
    ]
